### ISSUE TITLE
No ProgpowBlock on Rinkeby

### ISSUE THREAD

**Issue by cryptozeny** [ethereumprogpow/ethereumprogpow#2]
https://github.com/ethereumprogpow/ethereumprogpow/blob/9cdd8e8844cdd568546f5eab22be65d9eb51c891/params/config.go#L95

like
```go
		ConstantinopleBlock: nil,
		ProgpowBlock:        big.NewInt(7080000),
```

**Comment by naikmyeong** [comment]
RInkeby is POA testnet, they don't work for POW 😂
